# Generated by Django 6.0.1 on 2026-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция добавления имени и фамилии пользователя."""

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last name'),
        ),
    ]
