services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
    volumes:
      - ./DockerVolumes/db-data:/var/lib/postgresql/data
    ports:
      - "${BACKEND_DATABASE_EXTERNAL_PORT}:${BACKEND_DATABASE_PORT}"

  backend:
    build:
      context: ./AssignMate[Backend]
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./AssignMate[Backend]:/app
      - ./DockerVolumes/static:/app/static
      - ./DockerVolumes/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./AssignMate[Frontend]
      dockerfile: Dockerfile
      target: dev
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./AssignMate[Frontend]:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  tg_bot_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${TG_BOT_DATABASE_NAME}
      POSTGRES_USER: ${TG_BOT_DATABASE_USER}
      POSTGRES_PASSWORD: ${TG_BOT_DATABASE_PASSWORD}
    volumes:
      - ./DockerVolumes/tg-bot-db-data:/var/lib/postgresql/data
    ports:
      - "${TG_BOT_DATABASE_EXTERNAL_PORT}:${TG_BOT_DATABASE_PORT}"


  tg_bot:
    build:
      context: ./TgBot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - tg_bot_db
      - backend
