services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
    volumes:
      - ./DockerVolumes/db-data:/var/lib/postgresql/data
    ports:
      - "${BACKEND_DATABASE_EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BACKEND_DATABASE_USER} -d ${BACKEND_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./AssignMate[Backend]
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      BACKEND_DATABASE_HOST: db
      BACKEND_DATABASE_INTERNAL_PORT: 5432
      BACKEND_DJANGO_SUPERUSER_EMAIL: admin@mail.com
      BACKEND_DJANGO_SUPERUSER_PASSWORD: adminadmin
    volumes:
      - ./AssignMate[Backend]:/app
      - ./DockerVolumes/static:/app/static
      - ./DockerVolumes/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./AssignMate[Frontend]
      dockerfile: Dockerfile
      target: dev
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./AssignMate[Frontend]:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  tg_bot_db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${TG_BOT_DATABASE__NAME}
      POSTGRES_USER: ${TG_BOT_DATABASE__USER}
      POSTGRES_PASSWORD: ${TG_BOT_DATABASE__PASSWORD}
    volumes:
      - ./DockerVolumes/tg-bot-db-data:/var/lib/postgresql/data
    ports:
      - "${TG_BOT_DATABASE__EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TG_BOT_DATABASE__USER} -d ${TG_BOT_DATABASE__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  tg_bot:
    build:
      context: ./TgBot
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TG_BOT_DATABASE__HOST: tg_bot_db
      TG_BOT_DATABASE__INTERNAL_PORT: 5432
    depends_on:
      tg_bot_db:
        condition: service_healthy
      backend:
        condition: service_started

  vk_bot_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${VK_BOT_DATABASE__NAME}
      POSTGRES_USER: ${VK_BOT_DATABASE__USER}
      POSTGRES_PASSWORD: ${VK_BOT_DATABASE__PASSWORD}
    volumes:
      - ./DockerVolumes/vk-bot-db-data:/var/lib/postgresql/data
    ports:
      - "${VK_BOT_DATABASE__EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VK_BOT_DATABASE__USER} -d ${VK_BOT_DATABASE__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  vk_bot:
    build:
      context: ./VKBot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - vk_bot_db
      - backend
