services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: assignmate
      POSTGRES_USER: assignmate
      POSTGRES_PASSWORD: assignmate
    volumes:
      - ./DockerVolumes/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./AssignMate[Backend]
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./AssignMate[Backend]/.env
    volumes:
      - ./AssignMate[Backend]:/app
      - ./DockerVolumes/static:/app/static
      - ./DockerVolumes/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./AssignMate[Frontend]
      dockerfile: Dockerfile
      target: dev
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - ./AssignMate[Frontend]/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./AssignMate[Frontend]:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  tg_bot_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: assignmate_db
      POSTGRES_USER: assignmate_db
      POSTGRES_PASSWORD: assignmate_db
    volumes:
      - ./DockerVolumes/tg-bot-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  tg_bot:
    build:
      context: ./TgBot
      dockerfile: Dockerfile
    env_file:
      - ./TgBot/.env
    depends_on:
      - tg_bot_db
      - backend
