# Generated by Django 6.0.1 on 2026-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция добавления описания и материалов урока."""

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
    ]
