# Generated by Django 6.0.1 on 2026-01-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция добавления длительности урока."""

    dependencies = [
        ('courses', '0002_lesson_description_lesson_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
