# Generated by Django 6.0.1 on 2026-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция перехода course/lesson на safedelete."""

    dependencies = [
        ('courses', '0003_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='course',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
