# Generated by Django 6.0.1 on 2026-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция уникальности порядка уроков в курсе."""

    dependencies = [
        ('courses', '0004_remove_course_deleted_at_remove_course_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('course', 'order'), name='unique_course_and_order_when_not_deleted'),
        ),
    ]
