# Generated by Django 6.0.1 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция добавления кода приглашения курса."""

    dependencies = [
        ("courses", "0006_course_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="invite_code",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="invite_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
