# Generated by Django 6.0.2 on 2026-05-10 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lessonmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestaff',
            name='can_add_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursestaff',
            name='can_add_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursestaff',
            name='can_edit_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursestaff',
            name='can_review_homework',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonmaterial',
            name='file',
            field=models.FileField(upload_to='lesson_materials/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'png', 'jpg', 'jpeg', 'gif', 'mp4', 'mp3', 'wav', 'zip'))]),
        ),
    ]
