# Generated by Django 6.0.1 on 2026-01-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция изменения статуса submission."""

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('WAITED', 'Waited')], default='SUBMITTED', max_length=20),
        ),
    ]
