# Generated by Django 6.0.1 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция добавления порядка заданий."""

    dependencies = [
        ("assignments", "0003_remove_assignment_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["order"],
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("lesson", "order"),
                name="unique_lesson_and_order_when_not_deleted",
            ),
        ),
    ]
