# Generated by Django 6.0.1 on 2026-02-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция расширения типов заданий и ответов."""

    dependencies = [
        ('assignments', '0004_assignment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text_answer',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('FILL_BLANK', 'Fill blank'), ('SHORT_ANSWER', 'Short answer'), ('LONG_ANSWER', 'Long answer')], max_length=30),
        ),
        migrations.CreateModel(
            name='FillBlankAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_template', models.TextField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Fill blank assignment',
                'verbose_name_plural': 'Fill blank assignments',
            },
        ),
        migrations.CreateModel(
            name='FillBlankSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Fill blank submission',
                'verbose_name_plural': 'Fill blank submissions',
            },
        ),
        migrations.CreateModel(
            name='LongAnswerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_files', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_answer', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Long answer assignment',
                'verbose_name_plural': 'Long answer assignments',
            },
        ),
        migrations.CreateModel(
            name='LongAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_answer', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Long answer submission',
                'verbose_name_plural': 'Long answer submissions',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle_options', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Multiple choice assignment',
                'verbose_name_plural': 'Multiple choice assignments',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='multiple_choice_submissions', to='assignments.questionoption')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Multiple choice submission',
                'verbose_name_plural': 'Multiple choice submissions',
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Short answer assignment',
                'verbose_name_plural': 'Short answer assignments',
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Short answer submission',
                'verbose_name_plural': 'Short answer submissions',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffle_options', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='assignments.assignment')),
            ],
            options={
                'verbose_name': 'Single choice assignment',
                'verbose_name_plural': 'Single choice assignments',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_submissions', to='assignments.questionoption')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Single choice submission',
                'verbose_name_plural': 'Single choice submissions',
            },
        ),
        migrations.CreateModel(
            name='FillBlankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('correct_text', models.CharField(max_length=255)),
                ('fill_blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='assignments.fillblankassignment')),
            ],
            options={
                'verbose_name': 'Fill blank item',
                'verbose_name_plural': 'Fill blank items',
                'unique_together': {('fill_blank', 'position')},
            },
        ),
        migrations.CreateModel(
            name='FillBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('answer_text', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.fillblanksubmission')),
            ],
            options={
                'verbose_name': 'Fill blank answer',
                'verbose_name_plural': 'Fill blank answers',
                'unique_together': {('submission', 'position')},
            },
        ),
    ]
