# Generated by ChatGPT on 2026-03-10

from django.db import migrations, models


def migrate_submission_statuses(apps, schema_editor):
    """Мигрирует статусы ответов к новой схеме.

    Args:
        apps: Реестр моделей миграции.
        schema_editor: Редактор схемы БД.

    Returns:
        None.
    """
    Submission = apps.get_model("assignments", "Submission")
    Submission.objects.filter(status="REVIEWED").update(status="GRADED")
    Submission.objects.filter(status__in=["SUBMITTED", "WAITED"]).update(status="PENDING")
    Submission.objects.exclude(status__in=["PENDING", "REVISION", "GRADED"]).update(status="PENDING")


class Migration(migrations.Migration):
    """Миграция добавления дедлайна и статусов ответов."""

    dependencies = [
        ("assignments", "0005_remove_submission_selected_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="timeliness_status",
            field=models.CharField(
                choices=[("ON_TIME", "On time"), ("LATE", "Late")],
                default="ON_TIME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("REVISION", "Revision"), ("GRADED", "Graded")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_submission_statuses, migrations.RunPython.noop),
    ]
